name: terraform

on:
  push:
  workflow_dispatch:

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.0

      - name: terraform init
        working-directory: playground/http
        run: terraform init -input=false -no-color

      - name: terraform apply
        working-directory: playground/http
        run: terraform apply -auto-approve
