name: terraform

on:
  push:
    paths:
      - 'playground/http/**'
  workflow_dispatch:

jobs:
  terraform:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: playground/http
    steps:
      - uses: actions/checkout@v4

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.0

      - name: terraform init
        run: terraform init

      - name: terraform apply
        run: terraform apply -auto-approve
